version: '3'

services:
  unifi-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UNIFI_API_KEY=${UNIFI_API_KEY}
      - UNIFI_API_URL=${UNIFI_API_URL:-https://sitemanager.ui.com/api}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs